login:
    path: /login
    methods: GET
    controller: App\Controller\ListCitiesStreetsController::index

#logout:
#  path: /logout
#  controller: App\Controller\DefaultController::index
#
#cities:
#  path: /get_cities
#  controller: App\Controller\DefaultController::index
#
